interface ProductModel {
  admin_user_id: number
  admin_user_name: string
  banner_abbr_url: string
  begin_at: string
  circulation: number
  code_id: number
  created_at: string
  creator: string
  deleted_at: string
  end_at: string
  goods_no: string
  group_type: number
  id: number
  is_show: number
  model_id: string
  msg_product: []
  org_id: number
  product_amount_issue: string
  product_fiat_original: string
  product_fiat_original_as: string
  product_fiat_type_original: number
  product_fulfil_config: []
  product_fulfil_model: number
  product_limit_config: []
  product_limit_model: number
  product_msg_id: number
  product_name_cn: string
  product_name_en: string
  product_name_salt: string
  product_name_salt_as: string
  product_no: string
  product_pay_config: []
  product_pay_model: number
  product_price_original: string
  product_type: number
  product_type_config: []
  remark: string
  series_id: number
  sku_id: number
  status: number
  title: string
  updated_at: string
  user_id: number
}